### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by TonyRyan** [lemasato/POE-Trades-Helper#6]
The last version sorta worked for me. Occasionally it would just spam the letter 'v' in chat for some reason. It seemed if I alt tabbed to defocus the window, and then clicked the button, it would work as expected.

With this version I cannot get it to do anything in game. Just nothing happens.

I'm on Windows 10, running windowed fullscreen. Trades Helper is running as admin.

Any thoughts?

**Comment by lemasato** [comment]
The reason it was sending the V letter in chat was because the script was storing the message in the clipboard then using CTRL+V to send it.  
Could you try using the [.ahk version](https://raw.githubusercontent.com/lemasato/POE-Trades-Helper/master/POE%20Trades%20Helper.ahk)?  
Save the file as .ahk, then download [AutoHotKey](http://ahkscript.org/download/ahk-install.exe) and run .ahk file.

**Comment by TonyRyan** [comment]
AHK same issue. Click buttons, nothing happens.

**Comment by TonyRyan** [comment]
Nevermind. It appeared to be a background process interfering.

**Comment by lemasato** [comment]
Could you tell more about the background process? In case it ever happens to another user.

**Comment by TonyRyan** [comment]
It's pretty obscure. I was running Synergy which lets me share mouse keyboard between my desktop and laptop.
