### ISSUE TITLE
Feature Request: More custom hotkeys / scrolling stash tabs

### ISSUE THREAD

**Issue by Xebtria** [lemasato/POE-Trades-Helper#7]
1) I need more custom hotkeys
2) I previously had an AHK macro to scroll my stashtabs with ctrl mouseup/mousedown

nr. 2 was realized with this AHK code:

    ;cntl-mouse wheel up toggles stash tabs left
    ^WheelUp::Send {Left}  
   
    ;cntl-mouse wheel down toggles stash tabs right.
    ^WheelDown::Send {Right}  

could this be also realized with your program? Would be very helpful.

Thanks!

**Comment by lemasato** [comment]
6 hotkeys is the current maximum due to GUI restrictions.  
I may add some "advanced hotkeys" compatibility in the future.
Meanwhile, if you need more hotkeys, you can definitely use a script of your own!
If you want to make it so it only sends the inputs while POE is active, you could do:

`#SingleInstance Force
#NoEnv

GroupAdd, POEGame, ahk_exe PathOfExile.exe
GroupAdd, POEGame, ahk_exe PathOfExile_x64.exe
GroupAdd, POEGame, ahk_exe PathOfExileSteam.exe
GroupAdd, POEGame, ahk_exe PathOfExile_x64Steam.exe

#IfWinActive ahk_group POEGame
;   - Your Hotkeys -

**Comment by lemasato** [comment]
This is now possible since 1.5.
If you wish do bind CTRL+WheelUp to the Left Arrow, head into the Advanced Hotkeys and bind ^WheelUp to {Left}.

**Comment by Xebtria** [comment]
Just saw the update. Awesome! Thanks for your work :)
